/*do not edit this file*/

#include <stdio.h>

#ifdef TEST
#define TESTCODE
#endif
int g_unit_test_error_count = 0;
int g_unit_test_success_count = 0;
#ifdef TESTCODE

/*forward declarations*/

/*end of forward declarations*/

int test_main(void)
{
g_unit_test_error_count = 0;
g_unit_test_success_count = 0;
return g_unit_test_error_count;

}
#undef TESTCODE
#endif /*TEST*/
